



#---------------  Step 2:

# After running the model builder
# In ArcGIS, use Editor tool. Extent the NHD Line to the boundary of the watershed. 
# Select the NHD line

#----------------------Step 3

# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Generate_Points_Along_lines.py
# Created on: 2022-08-21 15:01:24.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Please change your working directory

# Local variables:
NHD_Line = "NHD Line"
NHD_Line_Points = "C:\\Users\\r_sigdel\\Documents\\ArcGIS\\Default.gdb\\NHD_Line_Points"
NHD_Line_Points__3_ = NHD_Line_Points
DEM_Result1_tif = "DEM_Result1.tif"

# Process: Generate Points Along Lines
arcpy.GeneratePointsAlongLines_management(NHD_Line, NHD_Line_Points, "DISTANCE", "30 Meters", "", "")

# Process: Extract Multi Values to Points
arcpy.gp.ExtractMultiValuesToPoints_sa(NHD_Line_Points, "DEM_Result1.tif DEM_Result1_12", "NONE")


#--------------------------- Step 4

# In ArcMap Export the Attribute Table in a Excel Sheet
